### ISSUE TITLE
Proposal: v5

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-colors#198]
## Current Interface

- Mixins
    - oColors($opts)
    - oColorsSetColor($name, $color)
    - oColorsSetUseCase($usecase, $property, $color)
    - oColorsFor($useCaseList, $propertyList, $textLevel)
- Functions
    - oColorsGetPaletteColor($name)
    - oColorsMix($color, $background, $percentage)
    - oColorsGetUseCase($usecase, $property)
    - oColorsGetColorFor($namelist, $property, $options)
    - oColorsGetTint($color, $brightness)
    - oColorsGetTextColor($backgroundd, $opacity, $warnings)
    - oColorsGetWCAGRating($col1, $col2)
    - oColorsCheckContrast($col1, $col2, $warnings)
    - oColorsColorBrightness($color)
    - oColorsColorLuminance($color)
    - oColorsGetContrastRatio($col1, $col2)
- Variables
    - o-colors-palette
    - o-colors-tints
    - o-colors-usecases

## Proposal

The proposal is split into vague categories to keep things interesting.

**To reduce the learning curve for using o-colors, for developers and uxd:**
- Remove mixins such as `oColorsGetUseCase` which return names instead of hex values. If we're getting a usecase programmatically we usually (always?) want the hex. o-colors could always find the name for a hex if needed.
- Make argument expectations more clear with `$color-name` over `$name` or `$color`. `$color-hex` instead of `$color` where a name is not expected. `$color` when either a hex or a name may be given.
- Remove `oColorsFor` mixin in favor of setting each property with `oColorsByName`. It's more transparent and removes some of the [less fun](https://github.com/Financial-Times/o-colors/issues/189) kind of magic.

**To improve ui reliability:**
- Error when a colour usecase is not found in `oColorsByUsecase`. Currently only warnings are output, but it could indicate a visually breaking issue. If a `null` value is acceptable, i.e. for the whitelabel brand, set the `$default` attribute to null e.g. `background: oColorsByUsecase($usecase: 'page', $property: 'background', $fallback: null);`.
- Explicitly namespace non-default colors and usecases with the project/component name `$project-name` e.g. `oColorsSetColor($project-name, $color-name, $color)`. This is currently required according to the readme but can be missed, making it hard to track down where a custom colour is defined -- or not defined, when it goes missing. If it does go missing error instead of returning null, as this may indicate a visually breaking change.

**Reduce build service bundle size:**
- Remove `.o-colors-palette-#{$name}` classes from the `oColors` primary mixin. It sets a background colour for each palette colour, plus a black or white colour, which is niche. Also remove usecase classes such as `.o-colors-link-hover-text`, these classes are largely not very useful except `.o-colors-page-background`, which could be reintroduced if a user needs it and can't use CSS Custom Properties.

**Other:**
- Remove deprecated colors from internal and whitelabel pallets, we may restore these in the future if needed (i.e. if an internal-ish brand wants to make use of `paper`).
- Remove `oColorsCheckContrast` and `oColorsGetWCAGRating`. We want to encourage users to use tools such as [Pa11y to access accessibility more thoroughly](https://github.com/Financial-Times/o-colors/issues/192) after build. But we would like to avoid Origami interfaces producing anything actively bad for accessibility, like creating poor contrasting colour combinations, so we'll keep `oColorsGetContrastRatio` to facilitate uses like `oColorsGetTextColor` which chooses a forground based on the highest contrast.

**Proposed Interface:**

```diff
Mixins

oColors($opts)
-oColorsSetColor($name, $color)
+oColorsSetColor($project-name, $color-name, $color-hex, $opts)
-oColorsSetUseCase($usecase, $property, $color)
+oColorsSetUseCase($project-name, $usecase, $colors, $opts)
-oColorsFor($useCaseList, $propertyList, $textLevel)
    
Functions

-oColorsGetPaletteColor($name)
+oColorsByName($color-name, $from: 'o-colors')
-oColorsGetUseCase($usecase, $property)
-oColorsGetColorFor($namelist, $property, $options)
+oColorsByUsecase($usecase, $property, $from: 'o-colors', $fallback)
oColorsMix($color, $background, $percentage)
-oColorsGetTint($color, $brightness)
+oColorsGetTint($color-name, $brightness)
-oColorsGetTextColor($backgroundd, $opacity, $warnings)
+oColorsGetTextColor($background, $opacity, $minimum-contrast: 'aa-normal')
-oColorsGetWCAGRating($col1, $col2)
-oColorsCheckContrast($col1, $col2, $warnings)
-oColorsGetContrastRatio($col1, $col2)
+oColorsGetContrastRatio($color-a, $color-b);
oColorsColorBrightness($color)
oColorsColorLuminance($color)
+oColorsGetPalette()

Variables

-o-colors-palette
-o-colors-tints
-o-colors-usecases
```

## Examples

Add a custom colour "storm" along with the likes of "paper" and "slate":
```scss
    @include oColorsSetColor('o-example', 'storm', #3682cf);
```

Deprecate the custom colour "storm", with a custom deprecation notice.
```scss
    @include oColorsSetColor('o-example', 'storm', #3682cf, (deprecated: 'use slate instead'));
```

Get a default colour "paper" and custom colour "storm":
```scss
    @include oColorsByName('paper'); // #fff1e5
    @include oColorsByName('storm', 'o-example'); // #3682cf
```

Set a custom usecase for "table stripes" along with the likes of "page background":
```scss
    @include oColorsSetUseCase('o-table', 'stripes', (
        'background': 'storm',
        'text': 'white'
    ), $opts);
```

Get a usecase "page background", get a custom usecase "stripes":
```scss
    body {
        background-color: oColorsByUsecase('page', 'background');
    }

    // using named arguments is nicer for custom colors and usecases
    tbody tr:nth-child(even) {
        background-color: oColorsByUsecase($from: 'o-table', $usecase: 'stripes', $property: 'background', $fallback: null); // fallback to null if not found
        color: oColorsByUsecase($from: 'o-table', $usecase: 'stripes', $property: 'text', $fallback: null,); // fallback to null if not found
    }
```

Iterate over colours available in the palette:
```scss
// Iterate over palette colour details.
// e.g. ('name': 'storm', 'from': 'o-example')
@each $color-details in oColorsGetPalette() {
    $color-name: map-get($color-details, 'name'); // color name e.g. 'storm'
    $from: map-get($color-details, 'from'); // project which added the color e.g. 'o-example'
    $color-hex: oColorsByName($color-name, $from), 'o-example'); // get the color e.g. #3682cf
}
```
