### ISSUE TITLE
Various new features

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-colors#51]
- use SASS maps and  sorter variable names
- provide back compatibility
- allow rgba and fallback colors
- add mixins to allow user to get a color triplet (border, bg and color/fg)

eg

``` scss

var $colors: oFtColorsUseCase(standout-button);

.o-ft-buttons--standout{
   @include oFtButtonColors($btn-colors);
}
```

and

``` scss
.o-ft-buttons--standout{
  background: oFtColorsUseCase(standout-button, disabled, bg);
}
```
- add common color related mixins

eg

``` scss
.o-ft-buttons--standout{
  @include oColorsBasic(standout-button);
}
```

``` css
.o-ft-buttons--standout{
  border-color: blue;
  background-color: blue;
  color: white;
}
```
