### ISSUE TITLE
Use !default instead of !global + test

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-colors#79]
In the use cases partial,

``` scss
@if (not variable-exists(o-colors-usecases)) {
    $o-colors-usecases: () !global;
}
```

Can be simplified in:

``` scss
$o-colors-usecases: () !default;
```
